# Generated by Django 4.1.7 on 2023-03-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='did',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
