# Generated by Django 4.1.7 on 2023-03-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencys', '0002_nfts_unique_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfts',
            name='symbol',
        ),
    ]
