# Generated by Django 4.1.7 on 2023-03-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencys', '0006_alter_cryptocurrency_ath_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='reddit_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
