# Generated by Django 4.1.7 on 2023-03-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencys', '0007_alter_cryptocurrency_reddit_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price_change_percentage_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
