# Generated by Django 4.1.7 on 2023-03-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencys', '0008_alter_cryptocurrency_price_change_percentage_24h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='categories',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='total_supply',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
