# Generated by Django 4.1.7 on 2023-03-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coindesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['category'],
                'unique_together': {('title', 'author', 'date')},
            },
        ),
    ]
