# Generated by Django 4.1.7 on 2023-03-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coindesk', '0002_alter_coindesk_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindesk',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
