# Generated by Django 4.1.7 on 2023-03-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coindesk', '0003_alter_coindesk_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coindesk',
            name='url',
        ),
        migrations.AddField(
            model_name='coindesk',
            name='sentiment',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
